language: node_js
node_js:
  - "0.10"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g karma
  - npm install -g bower

before_script:
  - npm install
  - bower install

script:
  - gulp travis